# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"

linters:
  default: none
  enable:
    - errcheck
    - gosimple
    - goimports
    - govet
    - ineffassign
    - godot
    - gosec
    - misspell
    - stylecheck
    - revive
    - staticcheck
    - typecheck
    - unused
    - gocyclo

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gofmt:
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"

run:
  timeout: 5m
